### ISSUE TITLE
Problem with directory

### ISSUE THREAD

**Issue by sbalgas** [boy1dr/3DWriter#1]
Hello!, I speack Spanish, but... I will try with English :D

I use this program in Linux, and as you know Linux has a different directory separator.

Backslash " \ " in Windows and Unix based use Slash " / " and for this reason I have a little error.

![image](https://cloud.githubusercontent.com/assets/6652374/22170434/17bd4378-df5c-11e6-99ed-739593a2bb8c.png)

I can't install visual studio in Linux xD! but maybe you can put " [Path.DirectorySeparatorChar](https://msdn.microsoft.com/en-us/library/system.io.path.directoryseparatorchar(v=vs.110).aspx) " :D

Thanks and Regards!!

**Comment by boy1dr** [comment]
Hi there :)
Thanks for the suggestion, I have updated the code to use Path.DirectorySeparatorChar instead of hard coded slashes. It ran ok in WINE and produced a valid gcode file but my linux wasn't able to render the preview window or show the font preview images.
I'll have a look in to why it behaved this way, hopefully it's an easy fix.
Let me know how this one goes

Chris.

**Comment by sbalgas** [comment]
Hi!
Thanks for update the code :D
I did not try with Wine, because I use [Mono Project](http://www.mono-project.com), so you can execute C# projects without problems "Except for the path".
Unfortunately, I can't compile this project because Mono is not compatible with ToolsVersion 14.0.
Yet with Mono, I can execute 3DWriter.exe in the Release folder and now it works perfectly.
For the moment, I need to calibrate my printer :D
Regards!
![image](https://cloud.githubusercontent.com/assets/6652374/22175125/acd79d34-dfcd-11e6-9f69-d1bb8ac212b5.png)
![img_20170120_232527](https://cloud.githubusercontent.com/assets/6652374/22175137/e1218938-dfcd-11e6-86e7-791f87379372.jpg)
