### ISSUE TITLE
Continuously going up and down

### ISSUE THREAD

**Issue by joeyvanderbeek** [boy1dr/3DWriter#12]
Hi there! First of all, thank you for this amazing piece of software!
I have a strange problem.

My first writing went perfect, absolutely beautiful. But when i made my second writing (Gcode), the printer seems to go up-and-down between every point it makes, just keeps going up and down, he is writing tho but not in the smooth way my first print did go.

Now, i opened the 2 different Gcode files in Notepad++, just because i was curious, and i found that my second file has continuously up and down commands for the G0... the first file doesn't...

Screenshot:

![image](https://user-images.githubusercontent.com/33073997/46243937-62efc380-c3d9-11e8-9f5a-cac8309397c6.png)

In the screenshot you  can see the difference. I played a lot with the settings in the 3dWriter program but can't seem to find the solution.. :-(

Do you have any idea how i can solve this? The settings i currently use in the program are as following: 

![image](https://user-images.githubusercontent.com/33073997/46243954-8c105400-c3d9-11e8-9df8-881b71de6140.png)

p.s. I know i changed the pen up and pen down values.. :)

O update 11:32 - i noticed that, when i close the program, reopen it and **change nothing** and then click on Generate G code, it is perfect. Only when i make changes, or generate multiple codes, the problem occurs.. maybe this can help. :)

Thanks in advance, best regards, Joey

**Comment by boy1dr** [comment]
Hi Joey, Thanks for letting me know about this issue.
I haven't been able to replicate it with either my source copy here or a fresh copy from github so i'm unsure at this stage what could be causing this behavior.

I have just released a new version (1.6.3) that includes all the settings in the GCode output file so we can see exactly what is going on here.

There has been some trouble in the past with decimals and comma's and other regional settings, is your system running MS Windows in plain US English ?

If you could grab the latest version and get me a copy of the gcode file which is showing the problem i should be able to determine what the cause is thanks.

**Comment by joeyvanderbeek** [comment]
Hi Chris,

Thanks so much for your reply. I’m using MS Windows in Dutch. I will try
the new version and give you a update! :-)

Regards,

Joey

Op do 4 okt. 2018 om 23:58 schreef Chris Mitchell <notifications@github.com>
