### ISSUE TITLE
Turkish font

### ISSUE THREAD

**Issue by dtserkanozkan** [boy1dr/3DWriter#16]
Hi. Thank you for this nice app. How to add or make new fonts, specially Turkish fonts.

**Comment by boy1dr** [comment]
Hi :)
I was working on a font editor but i just haven't had time to get back to it and finish it off. It's in the code but disabled on the menu bar. Feel free to mess around with it and see if you can get it working.

**Comment by dtserkanozkan** [comment]
Thanks. I don't have enoght knowledge to make or modify a program. So I have to wait for you to finish the project.

**Comment by dtserkanozkan** [comment]
Also I don't like to push anyone but this a Turkish font like cursive is really essential for my research. I couldn't find any other application like yours writing in single line. I hope you can finish the editor ASAP. Thank you for yor time.

**Comment by Nishanthb1** [comment]
Hello Chris Mitchell. Thank you for this amazing application.I'm doing a project for a blind School. I've asked my Computer Science friends to manipulate this codes as required for my Pen Plotter Project but they find it a bit confusing. Can you please explain me whats the XML file which you've added and which GCODE library did you use to make this one. I kindly request you to reply me for this or please share your mail address or mail me the answer to nishanthbabu8@gmail.com. It's easy if you can mail me because IDK to use github. It would be a very great help if you can help me. Thank you!

**Comment by Nishanthb1** [comment]
I've got this application with me for more than 8 months and asking every person i know to work on this but seems like no one has the knowledge on this.I'm actually not from computer's background.I study Civil Engineering in India.

**Comment by boy1dr** [comment]
Thanks for your interest in the project. I have been inspired to re-create it using HTML5 & Javascript. 
So far it works much better than the original and you can have as many different text elements using different fonts and sizes as you like.
It should get hosted sometime in the next week. i'll update this thread when it's live.
The font editor will be a few weeks off since it's very complicated but at least i know how to finish it now.

https://raw.githubusercontent.com/boy1dr/3DWriter/master/3dwriter_H5.png

**Comment by DirtyEngineer** [comment]
@boy1dr
Just an FYI in case you didn't know. GitHub offers a free web hosting service direct from a repository. https://pages.github.com/

**Comment by boy1dr** [comment]
@DirtyEngineer wow thanks i didn't know about that. i'll look into it :)

**Comment by dtserkanozkan** [comment]
@boy1dr
Thank you very much! I am looking forward to both of them :)

**Comment by Nishanthb1** [comment]
@boy1dr  That's great.I'm eagerly waiting for the new one and did you use any Gcode library or you wrote your own one? Also can you tell me how to debug your present version? Thank you for your quick reply!

**Comment by boy1dr** [comment]
I have published the new version here https://3dwriter.io
The site contains several help documents to keep visitors up to date on the progress. If you have any suggestions on it's development let me know.

**Comment by dtserkanozkan** [comment]
Thank you @boy1dr. Is there any way to execute it offline and also I tried it and there re big spaces between the line when hit"enter" to make seperate lines.

**Comment by boy1dr** [comment]
I'm moving this project to the web since that's what i do for a living and i don't have the time to maintain a C# version of it let alone learn the required skills to finish the C# editor off. And a big note here is that there IS a font editor in the C# version and should you wish it to be complete for your "research" purposes you may do so. Otherwise there is plenty of information on the internet about capturing a HTML page and viewing it offline if that is something you wish to do.

For this web version, the space between the lines can be adjusted by the changing the "line spacing" setting.

If your countries regional settings use coma's instead of period's for decimal separators this might be a problem and would appreciate some feedback.

**Comment by Nishanthb1** [comment]
Hello Mr.Chris Mitchell. Myself Nishanth from India studying degree in
civil engineering. I'm very much keen on your project since a very long
time. I wanted to use this application for blind school to write their
everyday sheets but our requirement was slightly different. So I thought of
manipulating the codes as required for our requirement. I've tried asking
pretty many coders to do this favor but one is understanding your code. Can
you please explain me the codes in brief. Sorry for my poor grammer! Your
help means a lot to me,Thank you !

**Comment by boy1dr** [comment]
Hi Nishanthb1, Sorry i don't understand what you are asking.

**Comment by Nishanthb1** [comment]
Hello Chris Mitchell!  Wish you a very Happy New Year!.
You please check out the file I've attached. If you observe it well,
there's starting number "1001" and an ending number "1500". All the empty
boxes will be usually written manually by hand. So i thought of building a
plotter for the blind school so that they can get the sheets done by a
machine easily instead paying money to some enterprises. And after some
days i luckily found out your application and it was super easy and simple
to use it.
When I tried typing all the numbers in the text field it took much more
time than writing it manually so i thought of building a tool that can
generate the numbers between the starting and ending number. And one more
issue was I couldn't fit all the numbers inside the each box (Check out the
image I've attached).
I gave this code to many of my friends to manipulate it for my requirement
but they were all unable to understand the code. So can you Please explain
me how does your application work?  It would be a great thing if you can
help me with the Project. This surely will be a great help for their school.
And actually those numbers written sheets are used for some mathematical
purposes by blind students apart from the braille script.
Excuse me for my grammatical mistake and poor English. If you haven't got
what I'm trying to tell please ask me once again.
THANK YOU!

**Comment by boy1dr** [comment]
nishanthb1, please use the github site to add images with your replies. at the bottom of email is "view it on github".

3DWriter uses many x/y coordinate pairs to create a path to be sent to a 3d printer to move a pen around and draw/write.

Sorry, i just don't understand your requirement. wouldn't a photo copier be faster?
How does pen writing relate to a blind persons school?

**Comment by boy1dr** [comment]
also, don't forget there's an online version of 3DWriter now. perhaps it can assist with your goal
https://3dwriter.io/
