### ISSUE TITLE
Can I donate a better font?

### ISSUE THREAD

**Issue by rw86347** [boy1dr/3DWriter#18]
Could you add this font to your webpage?

This font truly looks handwritten.  Not too perfect

https://www.dropbox.com/s/noop8x4fd291sqy/emizfont.ttf?dl=0

**Comment by boy1dr** [comment]
Sorry i missed this somehow.
I'm unable to use TTF font files because they are filled outline fonts. 3DWriter / Pen plotters use a series of strokes just like we do with hand writing.
Although possible to use TTF's with plotters with a lot of hard work it would look weird since the pen would have to flood fill the outlines using strokes.
Here's a dramatized re-enactment...
![PQR_filled](https://user-images.githubusercontent.com/5217188/68209510-42079200-001f-11ea-87d9-d6c2acad4104.jpg)
